name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t regnerdetioslows .

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.10.1
